### ISSUE TITLE
vue.common.dev.js:630 [Vue warn]: Missing required prop: "text"

### ISSUE THREAD

**Issue by stojankukrika** [codekraft-studio/vue-speech#1]
Hi, I get this error when add this `<vue-speech-recognition/>  <vue-speech-synthesis/>`in mine component.  I had register VueSpeech in boostrap file `import VueSpeech from '@codekraft-studio/vue-speech'` and `Vue.use(VueSpeech);'. Can you help me?

**Comment by b4dnewz** [comment]
yes, sorry it's mine fault, the documentation in the readme file is incomplete..
checkout the working demo [source code](https://github.com/codekraft-studio/vue-speech/blob/master/src/App.vue#L21-L22) to see how is used, the speech synthesis requires a given __text__ property with the text to sythetize

**Comment by stojankukrika** [comment]
OO thank you for a replay. And please find a little bit time to update readme. It's awesome package and will be nice to have a nice readme.

**Comment by b4dnewz** [comment]
yes I will update it as soon as possible with at least a getting started guide for the components.
thanks for using this plugin! If you have any user-feedback or suggestion about the usage feel free to say it!

**Comment by stojankukrika** [comment]
Hi,I didn't like to make new issue here because some developers count issues instead of some other things. Can you tell me how to solve this issue. When I click on record icon it didn't record me nothing and still blocked even I click on ask if need. I use chrome browser and app is run localy in virtual host: http://testproject.test  . Is there any issue with virtual host and did host need to be https to that feature works? Or I miss something.

**Comment by b4dnewz** [comment]
it should ask for permissions first, check if you haven't blocked permissions for that particular site (or all sites) check this [google reference](https://support.google.com/chrome/answer/2693767?co=GENIE.Platform%3DDesktop&hl=en) in case, eventually check if your microphone is available through the system.

Edit: Does it throw any error in console?

**Comment by b4dnewz** [comment]
unfortunately the online demo is no more available but you can try to clone the project locally and serve it with `npm run serve` it should start the development server with the old demo at [http://localhost:8080/](http://localhost:8080/) and you can try if you can record your voice with the recognition component

**Comment by stojankukrika** [comment]
Here is demo video for that:
https://streamable.com/gqwkk

And in console when I click on recording button it's just console log "Voice recognition ended."

**Comment by b4dnewz** [comment]
ok, I will take a look a it this afternoon when I come back from work and let you know what could be the problem, thanks for your patience by the way!

**Comment by stojankukrika** [comment]
Maybe I findout what is the issue with work on localhost: 
https://medium.com/@Carmichaelize/enabling-the-microphone-camera-in-chrome-for-local-unsecure-origins-9c90c3149339
maybe it will helps you and maybe you can mention in documentation ;)

**Comment by b4dnewz** [comment]
interesting! I will add it in the documentation.
actually I didn't know that before, since I mostly develop from localhost and is threat like a safe origin.
in your case probably depends on the fact that you are developing from a custom hostname and chrome is blocking you even if you click on allow because of the security policies.

I'm happy to hear that is working now, also few updates are coming soon since I realized this module needs few fixes and more features.

**Comment by stojankukrika** [comment]
It's happened because I use homestead and virtual host. I think that make that issue. (I send you friend request in linkedin so we can talk privatly :) )
